name: Go Environment
description: Download dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24.4
        cache: true
    
    - name: Install dependencies
      run: go mod download
      shell: bash