name: Go Environment
description: Download dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'
        cache: true
    
    - name: Install dependencies
      run: go mod download
      shell: bash