name: CI

on:
  push:
    branches: ["**"]
    paths-ignore:
      - "stats.yml"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "stats.yml"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-go

      - name: Run tests
        run: go test ./... -v
