name: Vercel Preview Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches-ignore:
            - main

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup-go

            - name: Run tests
              run: go test ./... -v

            - name: Run tests with coverage
              run: go test ./... -coverprofile=coverage.out

            - name: Display coverage
              run: go tool cover -func=coverage.out

    Deploy-Preview:
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Vercel CLI
              run: npm install --global vercel

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts
              run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}