name: Update Dependencies

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 0 1 */3 *' # Every three months on the 1st day
  workflow_dispatch: # Manual trigger

jobs:
  update-dependencies:
    name: Update Go Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup-go
      
      - name: Update dependencies
        run: |
          go get -u ./...
          go mod tidy
      
      - name: Run tests
        run: go test ./... -v
      
      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out
      
      - name: Check for changes
        id: git-check
        run: |
          git add -A
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "chore: update Go dependencies"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}